{% set name = "planetary-coverage" %}
{% set version = "1.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/planetary_coverage-{{ version }}.tar.gz
  sha256: be483ba59dcb4d2e8744af15d8579c57a6824bba0f4728ef06b23a7ffa5cddfc

build:
  entry_points:
    - kernel-download = planetary_coverage.cli:cli_kernel_download
    - mk-download = planetary_coverage.cli:cli_metakernel_download
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.10,<4.0
    - poetry-core >=1.0.0
    - pip
  run:
    - python >=3.8,<4.0
    - pillow >=10.0.0
    - matplotlib-base >=3.7.2
    - numpy >=1.25.0
    - spiceypy >=6.0.0
    - defusedxml >=0.7.1,<1.0.0

test:
  imports:
    - planetary_coverage
  requires:
    - pip
  commands:
    - pip check
    - kernel-download --help
    - mk-download --help

about:
  home: https://docs.planetary-coverage.org
  summary: Planetary coverage package
  description: |
    The planetary-coverage package is a toolbox to perform
    surface coverage analysis based on orbital trajectory
    calculations. Its main intent is to provide an easy way
    to compute observation opportunities of specific region
    of interest above the Galilean satellites for the
    ESA-JUICE mission but could be extended in the future
    to other space mission.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.md
  doc_url: https://docs.planetary-coverage.org
  dev_url: https://juigitlab.esac.esa.int/python/planetary-coverage

extra:
  recipe-maintainers:
    - seignovert
